{{- if .Values.wiremock.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wiremock-mappings
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-wiremock
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.wiremockMappings }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
