
bankHolidays:
  api:
    url: https://www.gov.uk

nonworking-days:
  datafile: /data/non-working_days.dat

# Postcode Lookup Service
os-postcode-lookup:
  url: https://api.os.uk/search/names/v1/find
  key: ${OS_POSTCODE_LOOKUP_API_KEY:}
  offline-mode: false

notifications:
  govNotifyApiKey: ${GOV_NOTIFY_API_KEY:some-gov-uk-notify-api-key}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}
  offline-mode: false
  env: ${LAUNCH_DARKLY_ENV:default}

role-assignment-service:
  api:
    url: http://localhost:4096

fees:
  api:
    service: civil money claims
    jurisdiction1: civil
    jurisdiction2: county court
    channel: default
    event: issue
    hearingEvent: hearing
    endpoint: /fees-register/fees/lookup
    jurisdiction2Hearing: civil
    keywords:
      fastTrackHrg: FastTrackHrg

pin-in-post:
  cui-respond-to-claim:
    url: ${CUI_URL_RESPOND_TO_CLAIM:http://localhost:3001/first-contact/start}
  cui-front-end:
    url: ${CUI_URL:http://localhost:3001}

document_management:
  userRoles: "caseworker-civil,caseworker-civil-solicitor"
  secured: ${DOCUMENT_MANAGEMENT_SECURED:true}
