tags:
  unspec-ccd-stack: false
postgresql:
  enabled: false
idam-pr:
  enabled: false

xui-webapp:
  enabled: false

camunda-bpm:
  enabled: false

java:
  applicationPort: 4000
  image: 'hmctspublic.azurecr.io/civil-damages/service:latest'
  ingressHost: civil-damages-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    LAUNCH_DARKLY_ENV: '{{ .Values.global.environment }}'
    IDAM_CLIENT_ID: unspec-service
    IDAM_CLIENT_REDIRECT_URI: https://unspec-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    MANAGE_CASE_UI_BASE_URL: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net
    SPRING_SECURITY_ENABLED: true
    CMC_DB_USERNAME: 'cmc@cmc-{{ .Values.global.environment }}'
    CMC_DB_HOST: cmc-{{ .Values.global.environment }}.postgres.database.azure.com
    CMC_DB_CONNECTION_OPTIONS: '?sslmode=require&gssEncMode=disable'
    CMC_DB_NAME: cmc
    CMC_DB_PORT: 5432
    REFERENCE_DATABASE_MIGRATION: false
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/realms/root/realms/hmcts
    FEES_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYMENTS_API_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCMOSIS_TORNADO_URL: https://docmosis-development.platform.hmcts.net
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEIGN_CLIENT_CONFIG_REMOTERUNTIMESERVICE_URL: http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEEXTERNALTASKSERVICE_URL: http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEREPOSITORYSERVICE_URL: http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest/
    SPRING_CLOUD_BOOTSTRAP_ENABLED: true
    RD_PROFESSIONAL_API_URL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

  keyVaults:
    unspec:
      resourceGroup: unspec
      secrets:
        - unspec-idam-client-secret
        - microservicekey-unspec-service
        - system-update-user-username
        - system-update-user-password
        - AppInsightsInstrumentationKey
        - docmosis-api-key
        - cmc-db-password
        - gov-notify-api-key
        - sendgrid-api-key
        - robotics-notification-sender
        - robotics-notification-recipient
        - launch-darkly-sdk-key
