apiVersion: v2
description: A Helm chart for unspec-service App
name: unspec-service
home: https://github.com/hmcts/unspec-service
version: 1.3.3
maintainers:
  - name: HMCTS Unspecified team

dependencies:
  - name: java
    version: 3.2.1
    repository: '@hmctspublic'
  - name: ccd
    version: 4.3.3
    repository: '@hmctspublic'
    tags:
      - unspec-ccd-stack
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.2.3
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: postgresql
    version: 8.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: camunda-bpm
    version: 0.0.9
    repository: '@hmctspublic'
    condition: camunda-bpm.enabled
